import test from "node:test";import assert from "node:assert/strict";
import {assessCapturedAuthenticationExchange} from "../src/protocol/authentication-exchange.mjs";
import {AUTH_RESPONSE_COLUMNS} from "../src/protocol/authentication-response.mjs";
import {AUTHENTICATION_BATCH_SHAPES} from "../src/protocol/authentication-batch-binding.mjs";
import {readFileSync} from "node:fs";
const loginShape=JSON.parse(readFileSync(new URL('../config/protocol-observations/authentication-request-shape.json',import.meta.url))).shape;
function request(){const v=[[10,120,"'N'"],[1,"'fixture'","'N'","'N'","'Y'","'fixture'","'secret'"],[...Array.from({length:5},()=>["'Y'","'Y'","''"]).flat(),"'fixture'"],[],[108]];const sql=AUTHENTICATION_BATCH_SHAPES.map((s,i)=>{let n=0;return(s??loginShape).replaceAll('<value>',()=>String(v[i][n++]));});return new URLSearchParams({connection:'EASYPAT_S_SSPAT',count:'5',command:'OTHERS',...Object.fromEntries(sql.map((s,i)=>['sql'+i,s]))}).toString();}
function response(id='fixture'){const b='----------x';const rows=[[{}],[{id,pw:'PRIVATE'}],[{urightcode:'R',_uread:'Y',_uwrite:'',_udelete:'',_uprint:'',_uattach:''}],[{}],[{}]];const rs=(c,r)=>c.join('\x01')+'\r\n'+c.map(x=>x==='pw'?'binary':x==='today'?'timestamp':'char').join('\x01')+'\r\n'+c.map(()=>30).join('\x01')+'\r\n'+c.map(()=>'r').join('\x01')+'\r\n'+c.map(x=>'"'+String(r[x]??'')+'"').join('\x01')+'\r\n';return {responseText:AUTH_RESPONSE_COLUMNS.map((c,i)=>b+'\r\nContent-Type: text/resultset\r\n\r\n'+rs(c,rows[i][0])).join('\r\n')+'\r\n'+b+'--\r\n',responseContentType:'multipart/mixed; boundary='+b+';charset=UTF-8'};}
test('requires both identity match and independently supplied cookie continuity',()=>{for(const [id,cookie,status]of[['fixture',true,'captured-successful-session-exchange-observed'],['fixture',false,'authentication-outcome-not-established'],['other',true,'authentication-outcome-not-established']]){const r=assessCapturedAuthenticationExchange({requestCopied:request(),...response(id),framing:'observed-jbori',cookieContinuity:cookie});assert.equal(r.status,status);assert.equal(r.liveAuthenticationVerified,false);assert.ok(!JSON.stringify(r).includes('PRIVATE'));}});
