import assert from "node:assert/strict";
import test from "node:test";
import {compileAttachmentInsert,compileHistoryBatch,compileProgressInsertBatch,DOMESTIC_REPORT_MUTATION_TEMPLATE_COLUMNS as C} from "../src/protocol/domestic-report-upload-mutation-template.mjs";

const progressValues=Object.fromEntries(C.progress.map(column=>[column,"NULL"]));Object.assign(progressValues,{idx_parent:"'31883'",d_opinion:"'2026-9-21'",clerk_op:"'장진태'",op_doc:"'특허 출원 진행 요청'",sort:"(SELECT 1)"});
const progress={templateId:"matter-progress.insert-batch.v1",command:"OTHERS",statements:[`INSERT INTO opms_app_proc (${C.progress.join(",")}) VALUES (${C.progress.map(column=>progressValues[column]).join(",")})`,`SELECT SCOPE_IDENTITY() AS 'idx'`]};
const attachmentValues=Object.fromEntries(C.attachment.map(column=>[column,"''"]));Object.assign(attachmentValues,{GRP_KEY:"'31883'",DOC_NUM:"'171151'",REG_DATE:"GETDATE()",USR_DATE:"NULL",FILE_NAME:"N'test.txt'",FILE_NAME_UPLOAD:"'generated_name'",FILE_SIZE:"'0'",DOWN_COUNT:"'0'",MUNAME:"'장진태'"});
const attachment={templateId:"matter-progress.attach-insert.v1",command:"INSERT",statements:[`INSERT INTO opms_attach (${C.attachment.join(",")}) VALUES (${C.attachment.map(column=>attachmentValues[column]).join(",")})`]};
const history=value=>`INSERT INTO opms_history (${C.history.join(",")}) VALUES ('31883','171151','proc',GETDATE(),'진행사항','field','',${JSON.stringify(value).replaceAll('"',"'")},'EDT10','장진태')`;
const histories={templateId:"matter-progress.history-batch.v1",command:"OTHERS",statements:[history("2026-09-21"),history("장진태"),history("특허 출원 진행 요청"),history("특허 출원 진행 요청")]};

test("binds only trusted progress values and retains generated-identity query",()=>{const value=compileProgressInsertBatch({envelope:progress,matterIdentity:"98765",reportDate:"2026-09-22",assignee:"장진태",reportDocument:"의견서 및 보정서 제출 요청"});assert.match(value.statements[0],/'98765'/);assert.match(value.statements[0],/'2026-9-22'/);assert.match(value.statements[0],/'의견서 및 보정서 제출 요청'/);assert.equal(value.statements[1],progress.statements[1]);});
test("binds server-derived identities and file metadata to attachment INSERT",()=>{const value=compileAttachmentInsert({envelope:attachment,matterIdentity:"98765",progressIdentity:"222222",assignee:"장진태",fileName:"보고서.pdf",fileSizeBytes:1234,uploadedFileName:"upload/app_proc/2026/09/21/20260921_72760312.pdf"});assert.match(value.statements[0],/'98765'/);assert.match(value.statements[0],/'222222'/);assert.match(value.statements[0],/N'보고서\.pdf'/);assert.match(value.statements[0],/'1234'/);});
test("binds all four audit rows and rejects a changed captured template",()=>{const value=compileHistoryBatch({envelope:histories,matterIdentity:"98765",progressIdentity:"222222",reportDate:"2026-09-22",assignee:"장진태",reportDocument:"의견서 및 보정서 제출 요청"});assert.equal(value.statements.length,4);assert.ok(value.statements.every(statement=>statement.includes("'98765'")&&statement.includes("'222222'")));const changed=structuredClone(histories);changed.statements[0]=changed.statements[0].replace("opms_history","other");assert.throws(()=>compileHistoryBatch({envelope:changed,matterIdentity:"98765",progressIdentity:"222222",reportDate:"2026-09-22",assignee:"장진태",reportDocument:"특허 출원 진행 요청"}));});
