import assert from "node:assert/strict";
import {EventEmitter} from "node:events";
import test from "node:test";
import {buildDomesticReportMultipartUpload,createDomesticReportMutationTransport,EASYPAT_MUTATION_ENDPOINT,EASYPAT_UPLOAD_ENDPOINT} from "../src/protocol/domestic-report-mutation-transport.mjs";

function mock(response={statusCode:200,headers:{"content-type":"text/integer"},chunks:["1"]}){const calls=[];const request=(url,options,callback)=>{calls.push({url,options,body:null});const req=new EventEmitter();req.end=body=>{calls.at(-1).body=body;const res=new EventEmitter();res.statusCode=response.statusCode;res.headers=response.headers;res.complete=true;res.destroy=()=>{};callback(res);queueMicrotask(()=>{for(const chunk of response.chunks)res.emit("data",Buffer.from(chunk));res.emit("end");});};req.destroy=()=>{};return req;};return{request,calls};}
test("builds a bounded PDF-only multipart request matching the captured file-part media type",()=>{const file=Buffer.from("%PDF-test"),value=buildDomesticReportMultipartUpload({fileName:"보고서.pdf",bytes:file,boundary:"----------------fixture1234"});assert.match(value.contentType,/multipart\/form-data/);assert.ok(value.body.includes(file));assert.match(value.body.toString("utf8"),/Content-Type: application\/octet-stream/);assert.match(value.body.toString("utf8"),/filename="보고서\.pdf"/);assert.doesNotMatch(value.body.toString("utf8"),/C:\\|%[0-9A-F]{2}/);assert.throws(()=>buildDomesticReportMultipartUpload({fileName:"test.txt",bytes:file}));});
test("pins the mutation endpoint, TLS and cookie without redirects or retries",async()=>{const m=mock(),transport=createDomesticReportMutationTransport({request:m.request});const result=await transport({endpoint:EASYPAT_MUTATION_ENDPOINT,body:"fixed",contentType:"application/x-www-form-urlencoded; charset=utf-8",cookie:"JSESSIONID=private"});assert.equal(result.status,200);assert.equal(m.calls.length,1);assert.equal(m.calls[0].options.rejectUnauthorized,true);assert.equal(m.calls[0].options.agent,false);assert.equal(m.calls[0].options.headers.Cookie,"JSESSIONID=private");result.bytes.fill(0);});
test("permits multipart bytes only at the separate captured upload endpoint",async()=>{const m=mock({statusCode:200,headers:{"content-type":"text/html;charset=KSC5601"},chunks:["ok"]}),transport=createDomesticReportMutationTransport({request:m.request}),upload=buildDomesticReportMultipartUpload({fileName:"보고서.pdf",bytes:Buffer.from("%PDF-test"),boundary:"----------------fixture1234"});const result=await transport({endpoint:EASYPAT_UPLOAD_ENDPOINT,body:upload.body,contentType:upload.contentType,cookie:"JSESSIONID=private"});assert.equal(m.calls[0].url,EASYPAT_UPLOAD_ENDPOINT);result.bytes.fill(0);await assert.rejects(transport({endpoint:EASYPAT_MUTATION_ENDPOINT,body:upload.body,contentType:upload.contentType,cookie:"JSESSIONID=private"}));});
