import assert from "node:assert/strict";
import {mkdtemp,rm,writeFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {createHash} from "node:crypto";
import test from "node:test";
import {createDomesticReportMutationExecutor} from "../src/workflow/domestic-report-mutation-executor.mjs";
import {DOMESTIC_REPORT_MUTATION_TEMPLATE_COLUMNS as C} from "../src/protocol/domestic-report-upload-mutation-template.mjs";

const values=(columns,overrides)=>columns.map(column=>overrides[column]??"NULL");
const progress={templateId:"matter-progress.insert-batch.v1",command:"OTHERS",statements:[`INSERT INTO opms_app_proc (${C.progress.join(",")}) VALUES (${values(C.progress,{idx_parent:"'31883'",d_opinion:"'2026-9-21'",clerk_op:"'장진태'",op_doc:"'특허 출원 진행 요청'",sort:"(SELECT 1)"}).join(",")})`,`SELECT SCOPE_IDENTITY() AS 'idx'`]};
const attachment={templateId:"matter-progress.attach-insert.v1",command:"INSERT",statements:[`INSERT INTO opms_attach (${C.attachment.join(",")}) VALUES (${values(C.attachment,{DIV:"'proc'",GRP_KEY:"'31883'",DOC_NUM:"'171151'",DOC_NAME:"'진행사항'",REG_DATE:"GETDATE()",USR_DATE:"NULL",FILE_NAME:"N'test.txt'",FILE_NAME_UPLOAD:"'generated_name'",FILE_SIZE:"'0'",MEMO:"''",DOWN_COUNT:"'0'",CK_OPEN:"''",MUID:"'EDT10'",MUNAME:"'장진태'"}).join(",")})`]};
const historyValue=value=>`INSERT INTO opms_history (${C.history.join(",")}) VALUES ('31883','171151','proc',GETDATE(),'진행사항','field','',${JSON.stringify(value).replaceAll('"',"'")},'EDT10','장진태')`;
const history={templateId:"matter-progress.history-batch.v1",command:"OTHERS",statements:[historyValue("2026-09-21"),historyValue("장진태"),historyValue("특허 출원 진행 요청"),historyValue("특허 출원 진행 요청")]};
const rs="idx\r\nbigint\r\n20\r\nr\r\n\"171151\"\r\n",multipart=parts=>{const boundary="----------fixture";return{status:200,contentType:`multipart/mixed; boundary=${boundary};charset=UTF-8`,bytes:Buffer.from(parts.map(({type,body})=>`${boundary}\r\nContent-Type: ${type}\r\n\r\n${body}`).join("\r\n")+`\r\n${boundary}--\r\n`)}};

test("executes the captured order once and requires read-back verification",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"easypat-mutation-")),file=path.join(root,"보고서.pdf"),bytes=Buffer.from("%PDF-fixture");await writeFile(file,bytes);const calls=[];const responses=[multipart([{type:"text/integer",body:"1"},{type:"text/resultset",body:rs}]),{status:200,contentType:"text/html;charset=KSC5601",bytes:Buffer.from("2026/09/21/20260921_72760312.pdf")},{status:200,contentType:"text/integer",bytes:Buffer.from("1")},multipart(Array.from({length:4},()=>({type:"text/integer",body:"1"})))];const executor=createDomesticReportMutationExecutor({loadMutationTemplate:async id=>structuredClone([progress,attachment,history].find(item=>item.templateId===id)),getSessionCookie:async()=>"JSESSIONID=private",resolveMatterIdentity:async({matterReference})=>matterReference==="PPT251365"?"98765":null,transport:async request=>{calls.push({endpoint:request.endpoint,contentType:request.contentType,body:Buffer.isBuffer(request.body)?"binary":request.body});return responses.shift();},verifyReadBack:async input=>({verified:input.progressIdentity==="171151"})});try{const result=await executor({matterReference:"PPT251365",reportDate:"2026-09-22",assignee:"장진태",reportDocument:"의견서 및 보정서 제출 요청",fileName:"보고서.pdf",fileSizeBytes:bytes.length,sha256:createHash("sha256").update(bytes).digest("hex"),contentType:"application/pdf",localFilePath:file});assert.equal(result.status,"verified");assert.equal(calls.length,4);assert.match(calls[0].body,/command=OTHERS/);assert.equal(calls[1].body,"binary");assert.match(calls[2].body,/command=INSERT/);assert.match(calls[3].body,/count=4/);}finally{await rm(root,{recursive:true,force:true});}});

test("rejects caller-supplied identities and an invalid trusted resolver before transport",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"easypat-mutation-")),file=path.join(root,"보고서.pdf"),bytes=Buffer.from("%PDF-fixture");await writeFile(file,bytes);let transports=0;const executor=createDomesticReportMutationExecutor({loadMutationTemplate:async()=>{throw new Error("must not load");},getSessionCookie:async()=>{throw new Error("must not authenticate");},resolveMatterIdentity:async()=>"not-a-number",transport:async()=>{transports++;},verifyReadBack:async()=>({verified:false})}),input={matterReference:"PPT251365",reportDate:"2026-09-22",assignee:"장진태",reportDocument:"특허 출원 진행 요청",fileName:"보고서.pdf",fileSizeBytes:bytes.length,sha256:createHash("sha256").update(bytes).digest("hex"),contentType:"application/pdf",localFilePath:file};try{await assert.rejects(executor({...input,matterIdentity:"98765"}),error=>error.code==="DOMESTIC_REPORT_MUTATION_INPUT_REJECTED");await assert.rejects(executor(input),error=>error.code==="DOMESTIC_REPORT_MUTATION_MATTER_REJECTED");assert.equal(transports,0);}finally{await rm(root,{recursive:true,force:true});}});
