import assert from "node:assert/strict";
import test from "node:test";
import {Client} from "@modelcontextprotocol/sdk/client/index.js";
import {InMemoryTransport} from "@modelcontextprotocol/sdk/inMemory.js";
import {createEasyPatMcpServer} from "../src/mcp/server.mjs";

async function connected(fakeRuntime){
  const server=createEasyPatMcpServer({runtime:fakeRuntime});
  const client=new Client({name:"test-client",version:"1.0.0"});
  const [clientTransport,serverTransport]=InMemoryTransport.createLinkedPair();
  await server.connect(serverTransport);await client.connect(clientTransport);
  return{client,server};
}

function runtime(){return{status:()=>({automaticAuthenticationReady:true,enabledTemplateCount:3,genericMatterSummaryEnabled:true,genericApplicationNumberSearchEnabled:true,genericProgressListingEnabled:true,genericDocumentListingEnabled:true,genericProgressDocumentListingEnabled:true,genericNoticeAttachmentListingEnabled:true,genericProgressDocumentDownloadEnabled:true,genericProgressDocumentExtractionEnabled:true,documentMatterBindingVerified:true,allowedOperations:["get-matter-detail","list-progress","list-documents","download-document"]}),getMatterSummary:async({matterReference})=>({matterReference,rightType:null,applicationKind:null,applicationDivision:null,applicationDate:null,applicationNumber:null,titleKorean:null,status:null}),searchByApplicationNumber:async({applicationNumber})=>({applicationNumber:applicationNumber.toUpperCase(),count:1,items:[{matterReference:"PT261130",applicationNumber:applicationNumber.toUpperCase(),rightType:"특허",titleKorean:"테스트",status:"진행"}]}),listProgress:async({matterReference})=>({matterReference,count:0,items:[]}),listDocuments:async({matterReference})=>({matterReference,count:0,items:[]}),listProgressDocuments:async({matterReference,progressDocument})=>({matterReference,progressDocument,count:0,items:[]}),listNoticeAttachments:async({matterReference,progressDocument})=>({matterReference,noticeKind:"opinion_submission",progressDocument,noticeDate:"2026-09-11",dueDate:"2027-01-11",sequence:"1",aggregateAttachmentCount:42,count:1,items:[{position:42,documentName:"중간서류",registeredAt:"2026-09-11 09:29:13.313",fileName:"official.fin",fileSizeBytes:10}]}),downloadProgressDocument:async({matterReference,position,expectedFileName})=>({matterReference,position,fileName:expectedFileName,fileSizeBytes:12,contentType:"application/pdf",sha256:"b".repeat(64),path:"C:\\safe\\file.pdf",downloaded:true,alreadyPresent:false,overwritten:false,automaticRetryPerformed:false,serverMutationPerformed:false,serverUploadPathReturned:false}),extractProgressDocumentPdf:async({matterReference,fileName})=>({matterReference,sourceFileName:fileName,sourceSha256:"c".repeat(64),pageCount:2,fields:{applicationType:null,applicant:null,inventorInstruction:null,practitioner:null,assignee:null,databaseManager:null,introducer:null,fee:null,estimateAndPowerOfAttorney:null,note:null},requestedMatterCount:null,requestedMatterPrefix:null,relatedMatterReferences:[],rawTextReturned:false,emailAddressesReturned:false,contactDetailsReturned:false,externalUploadPerformed:false})};}

test("lists nine scoped EasyPAT tools including application-number search",async()=>{const {client,server}=await connected(runtime());try{const listed=await client.listTools();assert.deepEqual(listed.tools.map(tool=>tool.name),["easypat_status","easypat_get_matter_summary","easypat_search_by_application_number","easypat_list_progress","easypat_list_documents","easypat_list_progress_documents","easypat_list_notice_attachments","easypat_download_progress_document","easypat_extract_progress_document_pdf"]);for(const name of ["easypat_get_matter_summary","easypat_list_progress","easypat_list_documents","easypat_list_progress_documents","easypat_list_notice_attachments","easypat_download_progress_document","easypat_extract_progress_document_pdf"]){const tool=listed.tools.find(item=>item.name===name);assert.match(JSON.stringify(tool.inputSchema),/PPT\|PT\|P\|T\|D/);}assert.deepEqual(Object.keys(listed.tools.find(tool=>tool.name==="easypat_search_by_application_number").inputSchema.properties),["applicationNumber"]);assert.ok(listed.tools.every(tool=>!JSON.stringify(tool.inputSchema).match(/sql|cookie|url/i)));}finally{await client.close();await server.close();}});

test("accepts full generic matter identities and exact application numbers",async()=>{const {client,server}=await connected(runtime());try{const summary=await client.callTool({name:"easypat_get_matter_summary",arguments:{matterReference:"PT261130"}});assert.equal(summary.isError,undefined);assert.equal(summary.structuredContent.matterReference,"PT261130");const application=await client.callTool({name:"easypat_search_by_application_number",arguments:{applicationNumber:"pct/kr2026/012345"}});assert.equal(application.isError,undefined);assert.equal(application.structuredContent.applicationNumber,"PCT/KR2026/012345");const documents=await client.callTool({name:"easypat_list_documents",arguments:{matterReference:"PT261129"}});assert.equal(documents.isError,undefined);assert.equal(documents.structuredContent.matterReference,"PT261129");const notice=await client.callTool({name:"easypat_list_notice_attachments",arguments:{matterReference:"P261487",progressDocument:"의견제출통지서",noticeDate:"2026-09-11"}});assert.equal(notice.isError,undefined);assert.equal(notice.structuredContent.count,1);const result=await client.callTool({name:"easypat_get_matter_summary",arguments:{matterReference:"PT261130' OR 1=1--"}});assert.equal(result.isError,true);const unsafe=await client.callTool({name:"easypat_search_by_application_number",arguments:{applicationNumber:"10-2026-%"}});assert.equal(unsafe.isError,true);}finally{await client.close();await server.close();}});

test("sanitizes runtime failures",async()=>{const fake=runtime();const {client,server}=await connected(fake);try{fake.listDocuments=async()=>{throw new Error("secret SQL and cookie");};const failed=await client.callTool({name:"easypat_list_documents",arguments:{matterReference:"P261793"}});assert.equal(failed.isError,true);assert.doesNotMatch(JSON.stringify(failed),/secret|SQL|cookie/);}finally{await client.close();await server.close();}});
