import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { analysisMailIndex, analysisPacket, analysisStatus, bindAnalysis, failAnalysis, ingestAnalysis, prepareAnalysis, reviewCandidate } from '../lib/analysis';
import { captureAcceptedRelationshipEntries, wikiDetail } from '../lib/wiki';
import { createMatter, databaseStatus, getMatter, importOutlookMail, updateEntityNote, withDatabase } from '../lib/work-db';
import { auditMailLinks } from '../lib/link-audit';
import { auditRelationshipCoverage } from '../lib/relationship-audit';
import { recordAuditFeedback } from '../lib/audit-feedback';
import { verifiedReferenceNotes } from '../lib/reference-review';

const temporaryRoot = mkdtempSync(path.join(os.tmpdir(), 'sspat-phase3-'));
process.env.SSPAT_WORK_DB_PATH = path.join(temporaryRoot, 'test.db');
process.chdir(path.resolve(__dirname, '..', '..', 'dashboard'));
try {
  assert.equal(databaseStatus().integrity, 'ok');
  const matter = createMatter({ ourRef: 'P260001', note: '사용자 비고는 보존' });
  importOutlookMail([{ entryId: 'phase3-mail', folderPath: '받은 편지함', direction: 'received', subject: 'P260001 요청', mailAt: '2026-09-10T16:00:00Z', body: '장진태님, 초안의 도면을 확인해 주세요. 2026-09-15까지 출원 지시 바랍니다.' }], { from: '2026-09-10T00:00:00Z', to: '2026-09-12T00:00:00Z', folders: ['받은 편지함'] });
  const mailId = String((analysisMailIndex()[0] as any).id);
  const evidence = [{ mailId, field: 'body_text', quote: '장진태님, 초안의 도면을 확인해 주세요.' }];
  const f = (value: unknown) => ({ value, confidence: 0.9, rationale: '명시적 요청', evidence });
  const start = (op: string) => {
    const prepared = prepareAnalysis(op, [mailId]);
    bindAnalysis(prepared.runId, { agentId: `test-fixture-${prepared.runId}`, model: prepared.route.model, effort: prepared.route.effort });
    return prepared.runId;
  };
  const result = (runId: string, candidates: any[]) => ({ schemaVersion: 1, runId, coverage: [{ mailId, outcome: 'candidate', reason: '검토 후보 생성' }], candidates });
  const runId = start('mail_fact_extraction');
  const c = { key: 'summary', kind: 'fact', entityType: 'mail', entityId: mailId, fields: { summary: f('초안 도면 확인 요청') } };
  assert.throws(() => ingestAnalysis({ ...result(runId, [c]), coverage: [] }), /모든 입력/);
  assert.throws(() => ingestAnalysis(result(runId, [{ ...c, fields: { summary: { ...f('거짓'), evidence: [{ ...evidence[0], quote: '원문에 없는 말' }] } } }])), /원본과 일치/);
  assert.equal(analysisStatus().candidates.length, 0);
  ingestAnalysis(result(runId, [c]));
  assert.equal(ingestAnalysis(result(runId, [c])).duplicate, true);
  assert.throws(() => ingestAnalysis(result(runId, [{ ...c, key: 'other' }])), /덮어쓸/);
  let candidate = analysisStatus().candidates.find(x => x.run_id === runId)!;
  reviewCandidate(candidate.id, { action: 'edit', expectedVersion: 1, values: { summary: '도면 확인 요청 수신' } });
  assert.equal(analysisStatus().knowledge[0].entry_date, '2026-09-11');
  assert.throws(() => reviewCandidate(candidate.id, { action: 'accept', expectedVersion: 1 }), /이미 검토/);
  assert.equal(getMatter(String(matter.matter.id)).matter.note, '사용자 비고는 보존');

  const actionRun = start('action_judgement');
  const action = { key: 'draft-check', kind: 'action', entityType: 'matter', entityId: String(matter.matter.id), fields: { required: f(true), title: f('도면 확인'), assignee: f('장진태'), dueDate: f(null), priority: f('보통') } };
  assert.throws(() => ingestAnalysis(result(actionRun, [{ ...action, fields: { ...action.fields, dueDate: f('2026-02-30') } }])), /실재하는/);
  ingestAnalysis(result(actionRun, [action]));
  candidate = analysisStatus().candidates.find(x => x.run_id === actionRun)!;
  reviewCandidate(candidate.id, { action: 'accept', expectedVersion: 1 });
  assert.equal(getMatter(String(matter.matter.id)).actions.length, 1);
  assert.equal(getMatter(String(matter.matter.id)).actions[0].manager, '장진태');

  const highRun = start('action_judgement');
  ingestAnalysis(result(highRun, [{ ...action, key: 'high', fields: { ...action.fields, title: f('출원 지시 검토'), dueDate: f('2026-09-15') } }]));
  const high = analysisStatus().candidates.find(x => x.run_id === highRun)!;
  assert.throws(() => reviewCandidate(high.id, { action: 'accept', expectedVersion: 1 }), /독립 고위험/);
  const verification = start('high_risk_verification');
  assert.equal(analysisPacket(verification).route.model, 'gpt-5.6-sol');
  ingestAnalysis(result(verification, [{ key: 'verify', kind: 'risk', entityType: 'candidate', entityId: high.id, fields: { verdict: f('confirmed') } }]));
  assert.throws(() => reviewCandidate(high.id, { action: 'edit', expectedVersion: 1, values: { required: true, title: '출원 지시 검토', assignee: '황현우', dueDate: '2026-09-15', priority: '보통' } }), /새 검증/);
  reviewCandidate(high.id, { action: 'accept', expectedVersion: 1 });
  assert.equal(getMatter(String(matter.matter.id)).actions.length, 2);

  const staleRun = start('action_judgement');
  ingestAnalysis(result(staleRun, [{ ...action, key: 'stale', fields: { ...action.fields, title: f('추가 도면 검토') } }]));
  candidate = analysisStatus().candidates.find(x => x.run_id === staleRun)!;
  updateEntityNote('matter', String(matter.matter.id), '새 확정 비고', Number(matter.matter.rowVersion));
  assert.throws(() => reviewCandidate(candidate.id, { action: 'accept', expectedVersion: 1 }), /확정값이 변경/);
  reviewCandidate(candidate.id, { action: 'reject', expectedVersion: 1 });
  const unbound = prepareAnalysis('mail_fact_extraction', [mailId]);
  assert.throws(() => bindAnalysis(unbound.runId, { agentId: 'fixture', model: 'wrong-model', effort: 'medium' }), /모델 라우팅/);
  assert.throws(() => ingestAnalysis(result(unbound.runId, [c])), /디스패치/);
  failAnalysis(unbound.runId, 'TEST_CANCELLED');
  const lowRun = start('mail_fact_extraction');
  ingestAnalysis(result(lowRun, [{ ...c, key: 'low-risk-verifier-veto' }]));
  const low = analysisStatus().candidates.find(x => x.run_id === lowRun)!;
  assert.equal(low.risk_level, 'low');
  const vetoRun = start('high_risk_verification');
  ingestAnalysis(result(vetoRun, [{ key: 'veto', kind: 'risk', entityType: 'candidate', entityId: low.id, fields: { verdict: f('rejected') } }]));
  assert.throws(() => reviewCandidate(low.id, { action: 'accept', expectedVersion: 1 }), /반려 또는 사람 검토/);
  const newerRun = start('mail_fact_extraction');
  ingestAnalysis(result(newerRun, [{ ...c, key: 'new-evidence' }]));
  const newer = analysisStatus().candidates.find(x => x.run_id === newerRun)!;
  importOutlookMail([{ entryId: 'new-mail-after-snapshot', folderPath: '보낸 편지함', direction: 'sent', subject: 'P260001 후속 회신', mailAt: '2026-09-11T16:00:00Z', body: '도면을 확인했습니다.' }], { from: '2026-09-11T00:00:00Z', to: '2026-09-13T00:00:00Z', folders: ['보낸 편지함'] });
  assert.throws(() => reviewCandidate(newer.id, { action: 'accept', expectedVersion: 1 }), /새 메일/);
  const noActionRun = start('action_judgement');
  const noAction = { key: 'no-current-action', kind: 'action', entityType: 'matter', entityId: String(matter.matter.id), fields: { required: f(false) } };
  ingestAnalysis(result(noActionRun, [noAction]));
  const noActionCandidate = analysisStatus().candidates.find(x => x.run_id === noActionRun)!;
  importOutlookMail([{ entryId: 'mail-after-no-action', folderPath: '받은 편지함', direction: 'received', subject: '일반 안내', mailAt: '2026-09-11T17:00:00Z', body: '새 안내입니다.' }], { from: '2026-09-11T00:00:00Z', to: '2026-09-13T00:00:00Z', folders: ['받은 편지함'] });
  assert.throws(() => reviewCandidate(noActionCandidate.id, { action: 'accept', expectedVersion: 1 }), /새 메일/);
  const freshNoActionRisk = start('high_risk_verification');
  ingestAnalysis(result(freshNoActionRisk, [{ key: 'fresh-no-action-verify', kind: 'risk', entityType: 'candidate', entityId: noActionCandidate.id, fields: { verdict: f('confirmed') } }]));
  reviewCandidate(noActionCandidate.id, { action: 'accept', expectedVersion: 1 });
  assert.equal(getMatter(String(matter.matter.id)).actions.length, 2);
  withDatabase(db => {
    assert.ok(Number(db.prepare('SELECT COUNT(*) n FROM user_feedback').get()!.n) >= 12);
    assert.equal(db.prepare('SELECT COUNT(*) n FROM decision_comparison WHERE eligible_for_eval=1').get()!.n, 0);
    assert.equal(db.prepare('PRAGMA integrity_check').get()!.integrity_check, 'ok');
    assert.equal(db.prepare('PRAGMA foreign_key_check').all().length, 0);
  });
  // Party proposals retain field-level evidence and must pass independent risk review.
  const partyRun = start('matter_linking');
  const party = { key: 'party', kind: 'link', entityType: 'mail', entityId: mailId, fields: { matterRef: f('P260001'), partyType: f('organization'), businessType: f('법인'), name: f('테스트 회사'), email: f(null), role: f('고객') } };
  ingestAnalysis(result(partyRun, [party]));
  const partyCandidate = analysisStatus().candidates.find(x => x.run_id === partyRun)!;
  assert.throws(() => reviewCandidate(partyCandidate.id, { action: 'accept', expectedVersion: 1 }), /독립 고위험/);
  const partyRisk = start('high_risk_verification');
  ingestAnalysis(result(partyRisk, [{ key: 'party-verify', kind: 'risk', entityType: 'candidate', entityId: partyCandidate.id, fields: { verdict: f('confirmed') } }]));
  reviewCandidate(partyCandidate.id, { action: 'accept', expectedVersion: 1 });
  assert.equal(getMatter(String(matter.matter.id)).organizations[0].name, '테스트 회사');
  assert.equal(getMatter(String(matter.matter.id)).organizations[0].businessType, '법인');
  const relationshipWiki = captureAcceptedRelationshipEntries();
  assert.equal(relationshipWiki.createdEntries, 1);
  assert.equal(captureAcceptedRelationshipEntries().duplicate, true);
  const organizationId = String(getMatter(String(matter.matter.id)).organizations[0].id);
  assert.match(wikiDetail('organization', organizationId).entries[0].content, /P260001의 고객/);
  const exactConfirmedRun = start('matter_linking');
  ingestAnalysis(result(exactConfirmedRun, [{ ...party, key: 'party-exact-confirmed-after-version-change' }]));
  const exactConfirmedCandidate = analysisStatus().candidates.find(x => x.run_id === exactConfirmedRun)!;
  const exactConfirmedRisk = start('high_risk_verification');
  ingestAnalysis(result(exactConfirmedRisk, [{ key: 'party-exact-confirmed-verify', kind: 'risk', entityType: 'candidate', entityId: exactConfirmedCandidate.id, fields: { verdict: f('confirmed') } }]));
  withDatabase(db => db.prepare('UPDATE organization SET row_version=row_version+1,updated_at=? WHERE id=?').run(new Date().toISOString(), organizationId));
  reviewCandidate(exactConfirmedCandidate.id, { action: 'accept', expectedVersion: 1 });
  assert.equal(getMatter(String(matter.matter.id)).organizations.length, 1);
  const relationshipAudit = auditRelationshipCoverage();
  assert.ok(relationshipAudit.findings.every((finding: any) => finding.matterRef !== 'P260001'));
  assert.equal(auditRelationshipCoverage().duplicate, true);
  assert.throws(() => reviewCandidate(partyCandidate.id, { action: 'accept', expectedVersion: 1 }), /이미 검토/);
  const personRun = start('matter_linking');
  assert.throws(() => ingestAnalysis(result(personRun, [{ ...party, fields: { ...party.fields, partyType: f('person') } }])), /자연인/);
  failAnalysis(personRun, 'TEST_INVALID_PERSON');
  const directRun = start('matter_linking');
  ingestAnalysis(result(directRun, [{ ...party, key: 'party-user-review', fields: { ...party.fields, name: f('테스트 회사 표기'), businessType: f('미정') } }]));
  const directCandidate = analysisStatus().candidates.find(x => x.run_id === directRun)!;
  assert.throws(() => reviewCandidate(directCandidate.id, { action: 'confirm_relationship', expectedVersion: 1, existingPartyId: organizationId, reason: '검증 전에 직접 확인 시도', values: { matterRef: 'P260001', partyType: 'organization', businessType: '법인', name: '테스트 회사', email: null, role: '고객' } }), /독립 검증이 없는/);
  const directRisk = start('high_risk_verification');
  ingestAnalysis(result(directRisk, [{ key: 'party-needs-review', kind: 'risk', entityType: 'candidate', entityId: directCandidate.id, fields: { verdict: f('needs_review') } }]));
  assert.throws(() => reviewCandidate(directCandidate.id, { action: 'accept', expectedVersion: 1 }), /사람 검토/);
  reviewCandidate(directCandidate.id, { action: 'confirm_relationship', expectedVersion: 1, existingPartyId: organizationId, reason: '사용자가 같은 회사이며 법인임을 직접 확인', values: { matterRef: 'P260001', partyType: 'organization', businessType: '법인', name: '테스트 회사', email: null, role: '고객' } });
  assert.equal(getMatter(String(matter.matter.id)).organizations.length, 1);
  assert.equal(analysisStatus().candidates.find(x => x.id === directCandidate.id)!.review_status, 'edited');
  assert.equal(analysisStatus().candidates.find(x => x.id === directCandidate.id)!.verifications[0].value, 'needs_review');
  // An old prefix link cannot authorize a party proposal or pass the audit.
  createMatter({ ourRef: 'P260001-S1' });
  importOutlookMail([{ entryId: 'series-audit', folderPath: '받은 편지함', direction: 'received', subject: 'P260001-S1', mailAt: '2026-09-11T16:00:00Z', body: 'P260002-X1 미확인 접미사' }], { from: '2026-09-11', to: '2026-09-13', folders: ['받은 편지함'] });
  const seriesMail = (analysisMailIndex() as any[]).find(m => m.subject === 'P260001-S1')!.id;
  withDatabase(db => db.prepare("INSERT INTO mail_matter_link(mail_id,matter_id,match_source,confidence,created_at) VALUES (?,?,'user_input',1,?)").run(seriesMail, String(matter.matter.id), new Date().toISOString()));
  const unsafe = prepareAnalysis('matter_linking', [seriesMail]);
  bindAnalysis(unsafe.runId, { agentId: 'fixture-series', model: unsafe.route.model, effort: unsafe.route.effort });
  const sf = (value: unknown) => ({ value, confidence: 1, rationale: 'fixture', evidence: [{ mailId: seriesMail, field: 'subject', quote: 'P260001-S1' }] });
  assert.throws(() => ingestAnalysis({ schemaVersion: 1, runId: unsafe.runId, coverage: [{ mailId: seriesMail, outcome: 'candidate', reason: 'fixture' }], candidates: [{ ...party, entityId: seriesMail, fields: { matterRef: sf('P260001'), partyType: sf('organization'), businessType: sf('미정'), name: sf('잘못된 회사'), email: sf(null), role: sf('고객') } }] }), /전체 사건번호/);
  failAnalysis(unsafe.runId, 'TEST_PREFIX_BLOCK');
  const beforeLinks = withDatabase(db => JSON.stringify(db.prepare('SELECT * FROM mail_matter_link ORDER BY mail_id,matter_id').all()));
  const audit = auditMailLinks();
  assert.ok(audit.findings.some((x: any) => x.kind === 'existing_link_review' && x.matterRef === 'P260001'));
  assert.ok(audit.findings.some((x: any) => x.kind === 'unknown_pattern' && x.matterRef === 'P260002-X1'));
  assert.equal(auditMailLinks().duplicate, true);
  const reviewFinding = analysisStatus().linkAudit.findings.find((x: any) => x.kind === 'unknown_pattern');
  const auditFeedback = recordAuditFeedback(reviewFinding.decisionId, { status: 'needs_follow_up', answer: '번호 체계를 추가로 확인한다.' });
  assert.equal(auditFeedback.reviewStatus, 'needs_user_input');
  assert.equal(recordAuditFeedback(reviewFinding.decisionId, { status: 'needs_follow_up', answer: '번호 체계를 추가로 확인한다.' }).duplicate, true);
  const directlyAnswered = analysisStatus().linkAudit.findings.find((x: any) => x.decisionId === reviewFinding.decisionId);
  assert.equal(directlyAnswered.userAnswer.answer, '번호 체계를 추가로 확인한다.');
  assert.equal(directlyAnswered.inheritedFeedback, false);
  assert.equal(directlyAnswered.feedbackSourceDecisionId, reviewFinding.decisionId);
  assert.equal(withDatabase(db => JSON.stringify(db.prepare('SELECT * FROM mail_matter_link ORDER BY mail_id,matter_id').all())), beforeLinks);
  withDatabase(db => db.prepare("UPDATE mail_matter_link SET match_source='user_confirmed_thread' WHERE mail_id=? AND matter_id=?").run(seriesMail, String(matter.matter.id)));
  const verifiedIndirect = auditMailLinks();
  assert.equal(verifiedIndirect.findings.some((x: any) => x.kind === 'existing_link_review' && x.mailId === seriesMail && x.matterRef === 'P260001'), false);
  const inheritedLinkFeedback = analysisStatus().linkAudit.findings.find((x: any) => x.kind === 'unknown_pattern' && x.matterRef === 'P260002-X1');
  assert.notEqual(inheritedLinkFeedback.decisionId, reviewFinding.decisionId);
  assert.equal(inheritedLinkFeedback.reviewStatus, 'not_reviewed');
  assert.equal(inheritedLinkFeedback.userAnswer.answer, '번호 체계를 추가로 확인한다.');
  assert.equal(inheritedLinkFeedback.inheritedFeedback, true);
  assert.equal(inheritedLinkFeedback.feedbackSourceDecisionId, reviewFinding.decisionId);
  recordAuditFeedback(inheritedLinkFeedback.decisionId, { status: 'resolved', answer: '새 감사에서 직접 확인했다.' });
  const overriddenLinkFeedback = analysisStatus().linkAudit.findings.find((x: any) => x.decisionId === inheritedLinkFeedback.decisionId);
  assert.equal(overriddenLinkFeedback.userAnswer.answer, '새 감사에서 직접 확인했다.');
  assert.equal(overriddenLinkFeedback.inheritedFeedback, false);
  assert.equal(overriddenLinkFeedback.feedbackSourceDecisionId, inheritedLinkFeedback.decisionId);

  // Repeated audit answers in the same millisecond must display and deduplicate the last insert.
  recordAuditFeedback(inheritedLinkFeedback.decisionId, { status: 'needs_follow_up', answer: '후속 자료가 필요하다.' });
  withDatabase(db => {
    db.prepare('UPDATE user_feedback SET created_at=? WHERE decision_item_id=?').run('2026-09-15T01:00:00.000Z', inheritedLinkFeedback.decisionId);
  });
  assert.equal(analysisStatus().linkAudit.findings.find((x: any) => x.decisionId === inheritedLinkFeedback.decisionId).userAnswer.answer, '후속 자료가 필요하다.');
  assert.equal(recordAuditFeedback(inheritedLinkFeedback.decisionId, { status: 'needs_follow_up', answer: '후속 자료가 필요하다.' }).duplicate, true);
  const auditBeforeInvalid = withDatabase(db => JSON.stringify(db.prepare('SELECT * FROM user_feedback ORDER BY rowid').all()));
  assert.throws(() => recordAuditFeedback(inheritedLinkFeedback.decisionId, { status: 'resolved', answer: '   ' }), /입력하세요/);
  assert.equal(withDatabase(db => JSON.stringify(db.prepare('SELECT * FROM user_feedback ORDER BY rowid').all())), auditBeforeInvalid);

  const coverageMatter = createMatter({ ourRef: 'P260003' });
  importOutlookMail([{ entryId: 'coverage-feedback', folderPath: '받은 편지함', direction: 'received', subject: 'P260003 관계 확인', mailAt: '2026-09-12T16:00:00Z', body: '출원인 관계 확인이 필요합니다.' }], { from: '2026-09-12', to: '2026-09-14', folders: ['받은 편지함'] });
  const coverageMail = (analysisMailIndex() as any[]).find(m => m.subject === 'P260003 관계 확인')!.id;
  auditRelationshipCoverage();
  const coverageFinding = analysisStatus().relationshipAudit.findings.find((x: any) => x.matterRef === 'P260003');
  recordAuditFeedback(coverageFinding.decisionId, { status: 'needs_follow_up', answer: '당사자 유형을 추가 확인한다.' });
  withDatabase(db => db.prepare("UPDATE mail_matter_link SET match_source='user_input' WHERE mail_id=? AND matter_id=?").run(coverageMail, String(coverageMatter.matter.id)));
  auditRelationshipCoverage();
  const inheritedCoverageFeedback = analysisStatus().relationshipAudit.findings.find((x: any) => x.matterRef === 'P260003');
  assert.notEqual(inheritedCoverageFeedback.decisionId, coverageFinding.decisionId);
  assert.equal(inheritedCoverageFeedback.reviewStatus, 'not_reviewed');
  assert.equal(inheritedCoverageFeedback.userAnswer.answer, '당사자 유형을 추가 확인한다.');
  assert.equal(inheritedCoverageFeedback.inheritedFeedback, true);
  assert.equal(inheritedCoverageFeedback.feedbackSourceDecisionId, coverageFinding.decisionId);
  // Reference notes are exact-ref, independently verified, read-only observations.
  const noteRun = prepareAnalysis('mail_fact_extraction', [seriesMail]);
  bindAnalysis(noteRun.runId, { agentId: 'reference-fact-fixture', model: noteRun.route.model, effort: noteRun.route.effort });
  const noteResult = { schemaVersion: 1, runId: noteRun.runId, coverage: [{ mailId: seriesMail, outcome: 'candidate', reason: '번호 원문 요약' }], candidates: [{key: 'ref-note', kind: 'fact', entityType: 'mail', entityId: seriesMail, fields: {summary: sf('P260001-S1 번호가 제목에 있다.')}}] };
  ingestAnalysis(noteResult);
  const noteCandidate = analysisStatus().candidates.find(x => x.run_id === noteRun.runId)!;
  const notes = (ref = 'P260001-S1') => withDatabase(db => verifiedReferenceNotes(db, seriesMail, ref));
  assert.equal(notes().length, 0, 'unverified facts must not appear as verified notes');
  const verifyNote = (verdict: string) => {
    const r = prepareAnalysis('high_risk_verification', [seriesMail]);
    bindAnalysis(r.runId, { agentId: `independent-note-${r.runId}`, model: r.route.model, effort: r.route.effort });
    ingestAnalysis({ ...noteResult, runId: r.runId, candidates: [{key:'verify-note',kind:'risk',entityType:'candidate',entityId:noteCandidate.id,fields:{verdict:sf(verdict)}}] });
  };
  verifyNote('confirmed');
  const feedbackBeforeNotes = withDatabase(db => JSON.stringify(db.prepare('SELECT * FROM user_feedback ORDER BY rowid').all()));
  assert.equal(notes().length, 1);
  assert.equal(notes('P260001').length, 0, 'base reference must not match a suffixed reference');
  assert.equal(withDatabase(db => JSON.stringify(db.prepare('SELECT * FROM user_feedback ORDER BY rowid').all())), feedbackBeforeNotes);
  const sourceBeforeNotes = withDatabase(db => db.prepare('SELECT body_text FROM mail_item WHERE id=?').get(seriesMail))!;
  withDatabase(db => db.prepare('UPDATE mail_item SET body_text=? WHERE id=?').run('원문 변경', seriesMail));
  assert.equal(notes().length, 0, 'changed source must hide stale observations');
  withDatabase(db => db.prepare('UPDATE mail_item SET body_text=? WHERE id=?').run(sourceBeforeNotes.body_text, seriesMail));
  verifyNote('needs_review');
  assert.equal(notes().length, 0, 'conflicting verification must hide notes');
  console.log('Phase 3 contracts, evidence, coverage, routing, idempotency, risk gate, feedback, KST date, confirmed-value protection and verified reference notes passed.');
} finally { rmSync(temporaryRoot, { recursive: true, force: true }); }
